/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import java.awt.event.ActionListener;
import java.io.Reader;
import java.sql.DriverManager;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import vistas.vistaHistorial;


/**
 *
 * @author Eduardo
 */
public class LogInVista extends javax.swing.JFrame {
    Connection con= null;
    Statement stmt = null;
    /**
     * Creates new form logInVista
     */
    public LogInVista(){
        initComponents();
        ImageIcon icono = new ImageIcon("C:\\Users\\Eduardo\\Documents\\NetBeansProjects\\logIn\\src\\Imagenes\\Yu-Gi-Oh!_Dungeon_Dice_Monsters_Logo.png");
        this.setIconImage(icono.getImage());
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btn_salir = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        btn_historial = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(736, 480));
        setPreferredSize(new java.awt.Dimension(736, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("User:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, -1));

        jLabel3.setText("Pass:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, -1, -1));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 90, 176, -1));

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 134, 176, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 80, -1));

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, -1));

        btn_login.setText("LogIn");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 170, 90, 40));

        btn_historial.setText("Consultar historial");
        btn_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historialActionPerformed(evt);
            }
        });
        getContentPane().add(btn_historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 340, 140, -1));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f896f02374bf381153ea51a8aba6a50c.jpg"))); // NOI18N
        imagen.setMaximumSize(new java.awt.Dimension(1920, 1460));
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
         System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        this.dispose();
        vistaRegistro VR = new vistaRegistro();
        VR.setLocation(600,300);
        VR.setVisible(true);
        VR.setTitle("Registro");
        VR.setResizable(false);

         
             
         
         

    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historialActionPerformed
        this.dispose();
        vistaHistorial cu = new vistaHistorial();
        cu.setLocationRelativeTo(null);
        cu.setVisible(true);


    }//GEN-LAST:event_btn_historialActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
      /*String nombreUsuario,contrasena;
        
      nombreUsuario = txtUser.getText();
      contrasena = txtPass.getText().toString();
      String sql = "SELECT nombreUsuario,pass FROM Usuarios WHERE nombreUsuario = '" + nombreUsuario +"' AND pass='" + contrasena +"'";
      try {
            
            String url = "jdbc:mysql://localhost:3306/login";
            String usuario = "root";
            String contraseña = "videojuego";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery(sql);
               rs.last();
               int confirmacion = rs.getRow();
               System.out.println(confirmacion);
                   if (confirmacion==1)
                   {
                       JOptionPane.showMessageDialog(null, "inicio de seción exitoso");
                       this.dispose();
                       vistaTablero v=new vistaTablero();
                       v.setVisible(true);
                       
                       
                       
                   }
                   else{
                       JOptionPane.showMessageDialog(null, "usuario o contraseña invalido");
                   }
                   this.txtUser.setText("");
                   this.txtPass.setText("");
               
               
               
               
               
               
               
               
      }catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"error al iniciar seción");
            }
      finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }*/
    }//GEN-LAST:event_btn_loginActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_historial;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPasswordField txtPass;
    public static javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

     public String getNombreUsuario(){
        return this.txtUser.getText();
    }

    public String getPassword(){
        return this.txtPass.getText();
    }

    public JButton getButtonBtnlogin()
    {
        return this.btn_login;
    }
    public JButton getSalir(){
        return this.btn_salir;
    }
    public void setTxtUserPass(){
        this.txtUser.setText("");
        this.txtPass.setText("");
    }


    
    //Método que hará que otra clase escuche lo que está sucediendo en esta vista
    public void agregarListener(ActionListener al)
    {
        this.btn_login.addActionListener(al);
    }
    
}
