/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Eduardo
 */
public class vistaHistorial extends javax.swing.JDialog {
   Connection con = null;
   Statement stmt = null;

   String titulos[] = {"id","Usuario","Password","Jefe de Terreno"};
   String fila[] = new String [4];
   DefaultTableModel modelo;

 

 
   public vistaHistorial(){
        
        initComponents();
        
        this.setTitle("consulta usuarios");
        this.setLocation(335,200);
        this.setResizable(false);
        ImageIcon icono = new ImageIcon("C:\\Users\\Eduardo\\Documents\\NetBeansProjects\\logIn\\src\\Imagenes\\Yu-Gi-Oh!_Dungeon_Dice_Monsters_Logo.png");
        this.setIconImage(icono.getImage());
       
            try {
            
            String url = "jdbc:mysql://localhost:3306/login";
            String usuario = "root";
            String contraseña = "videojuego";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery("select* from usuarios");


                modelo = new DefaultTableModel(null,titulos);
            
               while(rs.next()) {
                   
                   fila[0] = rs.getString("id");
                   fila[1] = rs.getString("nombreUsuario");
                   fila[2] = rs.getString("pass");
                   fila[3] = rs.getString("jefeTerreno");
                   
                   
                   modelo.addRow(fila);     
               }
                tabla_Historial.setModel(modelo);
                TableColumn ci = tabla_Historial.getColumn("id");
                ci.setMaxWidth(25);
                TableColumn cu = tabla_Historial.getColumn("Usuario");
                cu.setMaxWidth(165);
                TableColumn cp = tabla_Historial.getColumn("Password");
                cp.setMaxWidth(160);
                TableColumn cj = tabla_Historial.getColumn("Jefe de Terreno");
                cj.setMaxWidth(180);
               
        }
        catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }


// btn consultar  instanciar un objeto de la clase consultaUsuarios

    

       
    
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Historial = new javax.swing.JTable();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuRegistro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla_Historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_Historial);

        menuArchivo.setText("Archivo");

        menuRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuRegistro.setText("registro");
        menuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroActionPerformed(evt);
            }
        });
        menuArchivo.add(menuRegistro);

        barraMenu.add(menuArchivo);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroActionPerformed
        this.dispose();
        LogInVista login = new LogInVista();
        login.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_menuRegistroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuRegistro;
    private javax.swing.JTable tabla_Historial;
    // End of variables declaration//GEN-END:variables
}
