/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static vistas.LogInVista.txtPass;
import static vistas.LogInVista.txtUser;

/**
 *
 * @author Eduardo
 */
public class vistaRegistro extends javax.swing.JDialog {
     Connection con= null;
    Statement stmt = null;

    /**
     * Creates new form vistaRegistro
     */
    public vistaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_reg = new javax.swing.JButton();
        txt_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        cmb_JefeTerreno = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reg.setText("Registrar");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("USUARIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("JEFE DE TERRENO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 120, -1));

        cmb_JefeTerreno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige el jefe de terreno", "Jefe de FUERZA", "Jefe de VELOCIDAD", "Jefe de DEFENSA" }));
        cmb_JefeTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_JefeTerrenoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_JefeTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 220, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CONTRASEÑA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, 20));

        btn_menu.setText("Volver al menu principal");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/green-eyes-ultimate-dragon.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1040, 0, 1610, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void cmb_JefeTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_JefeTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_JefeTerrenoActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        this.dispose();
        LogInVista login = new LogInVista();
        login.setVisible(true);
        login.setLocation(600,300);
// TODO add your handling code here:
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
          String nombreUsuario,contrasena,jefeTerreno;
        
        nombreUsuario = txt_usuario.getText();
        contrasena = txt_password.getText().toString();
        jefeTerreno = cmb_JefeTerreno.getSelectedItem().toString();
       
    // TODO add your handling code here:
         if(txt_usuario.getText().equals("") || txt_password.getText().toString().equals("")||cmb_JefeTerreno.getSelectedItem().equals("Elige el jefe de terreno")){
             javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar los campos para el registro.");
         
         }
         else{
             try{
                String url = "jdbc:mysql://localhost:3306/login";
                String usuario = "root";
                String contraseña = "videojuego"; 
                Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ){ 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
                  stmt = con.createStatement(); 
                  stmt.executeUpdate("INSERT INTO usuarios VALUES('" + 0 + "','"+nombreUsuario+"','"+contrasena+"','"+jefeTerreno+"')");
                  System.out.println("Se ha agregado el usuario a la base de datos");
             }  
      
       } catch (InstantiationException ex) {
           Logger.getLogger(LogInVista.class.getName()).log(Level.SEVERE, null, ex);  // 
       } catch (IllegalAccessException ex) {
           Logger.getLogger(LogInVista.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(LogInVista.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(LogInVista.class.getName()).log(Level.SEVERE, null, ex);
       }
                   finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        {
        this.txt_usuario.setText("");
        this.txt_password.setText("");                     
    }
    }
         
             
         
         

    
                                        
     
                                             
            // TODO add your handling code here:
    }//GEN-LAST:event_btn_regActionPerformed

    /**
     * @param args the command line arguments
     */
   
       
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_reg;
    private javax.swing.JComboBox cmb_JefeTerreno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
